services:
  - type: web
    name: mes-system-backend
    env: node
    plan: free
    buildCommand: cd src/backend && npm install
    startCommand: cd src/backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000